apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argocd-test-app
  template:
    metadata:
      labels:
        app: argocd-test-app
    spec:
      containers:
      - image: ghcr.io/hayunofek/argocd-test:master
        name: argocd-test-app
        ports:
        - containerPort: 80
